### ISSUE TITLE
Can't get the example to work

### ISSUE THREAD

**Issue by crftwrk** [shaack/bootstrap-cookie-consent-settings#1]
Hello,

it seems that this is exactly what I'm looking for.

However, I was not able to get a working example. Not here with Github code and not by downloading here https://www.jqueryscript.net/other/cookie-consent-settings-modal.html.

Is it possible to provide a simple example with same settings as jqueryscripts? With linked Bootstrap and without confusing ads in index? Just an index.html and js file.

This will much more better to understand and reproduce your plugin.

Thank you

Basti

**Comment by shaack** [comment]
Hi, thanks for your inquiry. You find my example page here: https://shaack.com/projekte/bootstrap-cookie-consent-settings/
The one at jqueryscript is just a kind of uncertified copy, I have nothing to do with. You could also contact me under the email address in https://shaack.com if you need more detailed support. You can see the banner in the wild here https://residenzkonzerte.berlin and here https://orangerie-charlottenburg.com

**Comment by crftwrk** [comment]
Perfect! Exactly what I'm searching for.

Thank you
